#!/bin/sh

### This file is for cross-shell setup ###

# Load various functions
[ -f "$XDG_CONFIG_HOME/shell_common/functions.sh" ] && . "$XDG_CONFIG_HOME/shell_common/functions.sh"

## Init runtimes/languages ##

# Pyenv (python) setup
if [ -d "$HOME/.pyenv/bin" ]; then
  export PATH="$HOME/.pyenv/bin:$PATH"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

# Rbenv (ruby) Setup
if [ -d "$HOME/.rbenv/bin" ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# NVM (node) setup
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Go setup
if [ -d /usr/local/go ]; then
  export PATH=$PATH:/usr/local/go/bin
fi

